/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package actividad_1umi;
import javax.swing.JOptionPane;

/**
 *
 * @author dauzh
 */
public class JFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame.class.getName());

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfestatura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfpeso = new javax.swing.JTextField();
        jtfaceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("IMC HOSPITAL");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Peso en Kilogramos");

        jtfestatura.addActionListener(this::jtfestaturaActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Estatura en metros");

        jtfpeso.addActionListener(this::jtfpesoActionPerformed);

        jtfaceptar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfaceptar.setText("Aceptar");
        jtfaceptar.addActionListener(this::jtfaceptarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtfestatura, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtfpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jtfaceptar)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfestatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jtfaceptar)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfestaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfestaturaActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jtfestaturaActionPerformed

    private void jtfpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfpesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfpesoActionPerformed

    private void jtfaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfaceptarActionPerformed
        // TODO add your handling code here:
 try {
    String peso = jtfpeso.getText();
    String estatura = jtfestatura.getText();
    
    float p = Float.parseFloat(peso);
    float e = Float.parseFloat(estatura);
    
    float imc = p / (e * e);
    
    JOptionPane.showMessageDialog(null, "IMC: " + imc);
    
    if(imc < 18.5){
    JOptionPane.showMessageDialog(null, "BAJO PESO");
} else if(imc >= 18.5 && imc <= 24.5){
    JOptionPane.showMessageDialog(null, "NORMAL");
} else if(imc >= 25 && imc <= 29.9){
    JOptionPane.showMessageDialog(null, "SOBREPESO");
} else if(imc >= 30 && imc <= 34.9){
    JOptionPane.showMessageDialog(null, "OBESIDAD I");
} else if(imc >= 35 && imc <= 39.9){
    JOptionPane.showMessageDialog(null, "OBESIDAD II");
} else {
    JOptionPane.showMessageDialog(null, "OBESIDAD III");
}
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}

jtfpeso.setText("");
jtfestatura.setText("");
        
    }//GEN-LAST:event_jtfaceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jtfaceptar;
    private javax.swing.JTextField jtfestatura;
    private javax.swing.JTextField jtfpeso;
    // End of variables declaration//GEN-END:variables
}
